### ISSUE TITLE
Error installing dev-branch version.

### ISSUE THREAD

**Issue by juhacz** [kaliiiiiiiiii/Selenium-Driverless#114]
I'm trying to install the dev version of the library as I see there is already support for authorized proxies. This is positive news for me. Thank you
Unfortunately, after the command:
`pip install https://github.com/kaliiiiiiiii/Selenium-Driverless/archive/refs/heads/dev.zip`

I have an error:

```
(venv) PS V:\DEV\Projects\Python\driverless> pip install https://github.com/kaliiiiiiiiii/Selenium-Driverless/archive/refs/heads/dev.zip
Collecting https://github.com/kaliiiiiiiiii/Selenium-Driverless/archive/refs/heads/dev.zip
  Using cached https://github.com/kaliiiiiiiiii/Selenium-Driverless/archive/refs/heads/dev.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "V:\DEV\Projects\Python\driverless\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "V:\DEV\Projects\Python\driverless\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "V:\DEV\Projects\Python\driverless\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\TEMP\pip-build-env-fucz4toz\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\TEMP\pip-build-env-fucz4toz\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "C:\TEMP\pip-build-env-fucz4toz\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 2, in <module>
      ModuleNotFoundError: No module named 'selenium_driverless'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```
Os: Win11
Python 3.10.6.

**Comment by kaliiiiiiiiii** [comment]
Oh yep my bad, I'll fix that, thanks.

**Comment by kaliiiiiiiiii** [comment]
@juhacz this should be fixed now
