### ISSUE TITLE
Error when trying to open a driver through docker

### ISSUE THREAD

**Issue by darkTrapX0** [kaliiiiiiiiii/Selenium-Driverless#258]
```
2024-07-11 18:40:56 stderr: Traceback (most recent call last):
2024-07-11 18:40:56   File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1025, in _wrap_create_connection
2024-07-11 18:40:56 stderr:     return await self._loop.create_connection(*args, **kwargs)
2024-07-11 18:40:56            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-11 18:40:56   File "/usr/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
2024-07-11 18:40:56     raise exceptions[0]
2024-07-11 18:40:56   File "/usr/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
2024-07-11 18:40:56 stderr:     sock = await self._connect_sock(
2024-07-11 18:40:56            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-11 18:40:56   File "/usr/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
2024-07-11 18:40:56 stderr:     await self.sock_connect(sock, address)
2024-07-11 18:40:56   File "/usr/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
2024-07-11 18:40:56 stderr:     return await fut
2024-07-11 18:40:56            ^^^^^^^^^
2024-07-11 18:40:56   File "/usr/lib/python3.11/asyncio/selector_events.py", line 674, in _sock_connect_cb
2024-07-11 18:40:56 stderr:     raise OSError(err, f'Connect call failed {address}')
2024-07-11 18:40:56 ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 54589)
2024-07-11 18:40:56 The above exception was the direct cause of the following exception:
2024-07-11 18:40:56 Traceback (most recent call last):
2024-07-11 18:40:56   File "/usr/local/lib/python3.11/dist-packages/selenium_driverless/types/base_target.py", line 76, in _init
2024-07-11 18:40:56     res = await session.get(url, timeout=10)
2024-07-11 18:40:56           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-11 18:40:56   File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 581, in _request
2024-07-11 18:40:56 stderr:     conn = await self._connector.connect(
2024-07-11 18:40:56            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-11 18:40:56   File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 544, in connect
2024-07-11 18:40:56     proto = await self._create_connection(req, traces, timeout)
2024-07-11 18:40:56 stderr:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-11 18:40:56   File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 944, in _create_connection
2024-07-11 18:40:56 stderr:     _, proto = await self._create_direct_connection(req, traces, timeout)
2024-07-11 18:40:56 stderr:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-11 18:40:56   File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1257, in _create_direct_connection
2024-07-11 18:40:56 stderr:     raise last_exc
2024-07-11 18:40:56   File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1226, in _create_direct_connection
2024-07-11 18:40:56 stderr:     transp, proto = await self._wrap_create_connection(
2024-07-11 18:40:56                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-11 18:40:56   File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1033, in _wrap_create_connection
2024-07-11 18:40:56     raise client_error(req.connection_key, exc) from exc
2024-07-11 18:40:56 aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 127.0.0.1:54589 ssl:default [Connect call failed ('127.0.0.1', 54589)]
2024-07-11 18:40:56 During handling of the above exception, another exception occurred:
2024-07-11 18:40:56 Traceback (most recent call last):
2024-07-11 18:40:56   File "/app/controllers/lilililili/lilililili_python/app.py", line 476, in <module>
2024-07-11 18:40:56 stderr:     asyncio.run(main())
2024-07-11 18:40:56   File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
2024-07-11 18:40:56     return runner.run(main)
2024-07-11 18:40:56            ^^^^^^^^^^^^^^^^
2024-07-11 18:40:56   File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
2024-07-11 18:40:56     return self._loop.run_until_complete(task)
2024-07-11 18:40:56            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-11 18:40:56   File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
2024-07-11 18:40:56     return future.result()
2024-07-11 18:40:56            ^^^^^^^^^^^^^^^
2024-07-11 18:40:56   File "/app/controllers/lilililili/lilililili_python/app.py", line 390, in main
2024-07-11 18:40:56 stderr:     async with webdriver.Chrome(options=config_instance) as browser:
2024-07-11 18:40:56   File "/usr/local/lib/python3.11/dist-packages/selenium_driverless/webdriver.py", line 128, in __aenter__
2024-07-11 18:40:56     await self.start_session()
2024-07-11 18:40:56   File "/usr/local/lib/python3.11/dist-packages/selenium_driverless/webdriver.py", line 260, in start_session
2024-07-11 18:40:56 stderr:     self._base_target = await BaseTarget(host=self._host, is_remote=self._is_remote,
2024-07-11 18:40:56                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-11 18:40:56   File "/usr/local/lib/python3.11/dist-packages/selenium_driverless/types/base_target.py", line 81, in _init
2024-07-11 18:40:56     raise asyncio.TimeoutError(
2024-07-11 18:40:56 TimeoutError: Couldn't connect to chrome within 30 seconds
```

code:
from selenium_driverless import webdriver
from selenium_driverless.types.by import By

    config_instance = webdriver.ChromeOptions()
    config_instance.add_argument("--no-sandbox")
    config_instance.add_argument("--disable-dev-shm-usage")
    config_instance.add_argument("--disable-gpu")
    config_instance.add_argument("--disable-setuid-sandbox")
    
    async with webdriver.Chrome(options=config_instance) as browser:
    
    
    (+ more code redacted, but works perfect in windows 10.

**Comment by kaliiiiiiiiii** [comment]
Verry likely, it's juct chrome having crashed.
Checkout what `webdriver.Chrome(options, debug+True)` reports you.

Closing as probably an issue with your env
