### ISSUE TITLE
Problems with using a package on Linux

### ISSUE THREAD

**Issue by A-B-asdf** [kaliiiiiiiiii/Selenium-Driverless#274]
I'm using ubuntu 22.04, python 3.10.12
I tried to install the package via `python3 -m pip install selenium-driverless` and run the default example code from readme.
I had this error:
```Traceback (most recent call last):
  File "/home/alex/0/Twitch-Channel-Points-Miner-v2/asdf.py", line 1, in <module>
    from selenium_driverless import webdriver
  File "/home/alex/.local/lib/python3.10/site-packages/selenium_driverless/webdriver.py", line 43, in <module>
    from selenium_driverless.scripts.switch_to import SwitchTo
  File "/home/alex/.local/lib/python3.10/site-packages/selenium_driverless/scripts/switch_to.py", line 29, in <module>
    from selenium_driverless.types.target import TargetInfo, Target
  File "/home/alex/.local/lib/python3.10/site-packages/selenium_driverless/types/target.py", line 26, in <module>
    from selenium_driverless.utils.utils import safe_wrap_fut
  File "/home/alex/.local/lib/python3.10/site-packages/selenium_driverless/utils/utils.py", line 20, in <module>
    DATA_DIR = user_data_dir(appname="selenium-driverless", appauthor="kaliiiiiiiiii", ensure_exists=True)
TypeError: user_data_dir() got an unexpected keyword argument 'ensure_exists'```
Ok, I tried to fast resolve this by removing unsupported argument, than i had this:
```Traceback (most recent call last):
  File "/home/alex/0/Twitch-Channel-Points-Miner-v2/asdf.py", line 24, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/alex/0/Twitch-Channel-Points-Miner-v2/asdf.py", line 8, in main
    async with webdriver.Chrome(options=options) as driver:
  File "/home/alex/.local/lib/python3.10/site-packages/selenium_driverless/webdriver.py", line 129, in __aenter__
    await self.start_session()
  File "/home/alex/.local/lib/python3.10/site-packages/selenium_driverless/webdriver.py", line 150, in start_session
    await is_first_run()
  File "/home/alex/.local/lib/python3.10/site-packages/selenium_driverless/utils/utils.py", line 124, in is_first_run
    await write(path, __version__, sel_root=False)
  File "/home/alex/.local/lib/python3.10/site-packages/selenium_driverless/utils/utils.py", line 92, in write
    async with aiofiles.open(path, "w+", encoding=encoding) as f:
  File "/home/alex/.local/lib/python3.10/site-packages/aiofiles/base.py", line 63, in __aenter__
    return await self
  File "/home/alex/.local/lib/python3.10/site-packages/aiofiles/base.py", line 59, in __await__
    self._obj = yield from self._coro.__await__()
  File "/home/alex/.local/lib/python3.10/site-packages/aiofiles/threadpool/__init__.py", line 92, in _open
    f = await loop.run_in_executor(executor, cb)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/home/alex/.local/share/selenium-driverless/is_first_run'```
It seems that I do something wrong or there are some problems with supporting this package on ubuntu

**Comment by kaliiiiiiiiii** [comment]
what package & version was it? Platformdirs?
