### ISSUE TITLE
AttributeError: 'ClientConnection' object has no attribute 'open' when trying to use "new_context = await driver.new_context()"

### ISSUE THREAD

**Issue by FelipeCabelloE** [kaliiiiiiiiii/Selenium-Driverless#284]
Hello!

My code looks something like this:

```python
async def main():
    options = webdriver.ChromeOptions()
    async with webdriver.Chrome(options=options) as driver:
        await driver.get(
            "https://example.com/",
            wait_load=True,
            timeout=60,
        )

        new_context = await driver.new_context()

asyncio.run(main())
```

When I try to run it I get this traceback, maybe related to the `Websockets` library

```bash
Traceback (most recent call last):
  File "/home/ubuntu/git/modern-html-scraping/async-scrapper.py", line 124, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/ubuntu/git/modern-html-scraping/async-scrapper.py", line 118, in main
    new_context = await driver.new_context()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/git/modern-html-scraping/.venv/lib/python3.12/site-packages/selenium_driverless/webdriver.py", line 374, in new_context
    await self.ensure_extensions_incognito_allowed()
  File "/home/ubuntu/git/modern-html-scraping/.venv/lib/python3.12/site-packages/selenium_driverless/webdriver.py", line 557, in ensure_extensions_incognito_allowed
    await page.close()
  File "/home/ubuntu/git/modern-html-scraping/.venv/lib/python3.12/site-packages/selenium_driverless/types/target.py", line 673, in close
    await self._socket.close()
  File "/home/ubuntu/git/modern-html-scraping/.venv/lib/python3.12/site-packages/cdp_socket/socket.py", line 207, in close
    if self._ws.open:
       ^^^^^^^^^^^^^
AttributeError: 'ClientConnection' object has no attribute 'open'
```

I'm in wsl2 using python 3.12.3

**Comment by kaliiiiiiiiii** [comment]
https://github.com/kaliiiiiiiiii/CDP-Socket/issues/30
Duplicate
