### ISSUE TITLE
Remove `selenium` dependency

### ISSUE THREAD

**Issue by Acanis87** [kaliiiiiiiiii/Selenium-Driverless#290]
Hey,

Driverless isnt using Selenium (anymore?), but its still an dependency:

> Traceback (most recent call last):
>   File "C:\Users\...\...\main.py", line 3, in <module>
>     from selenium_driverless import webdriver
>   File "C:\Users\...\...\.venv\Lib\site-packages\selenium_driverless\webdriver.py", line 43, in <module>
>     from selenium_driverless.scripts.switch_to import SwitchTo
>   File "C:\Users\...\...\.venv\Lib\site-packages\selenium_driverless\scripts\switch_to.py", line 29, in <module>
>     from selenium_driverless.types.target import TargetInfo, Target
>   File "C:\Users\...\...\.venv\Lib\site-packages\selenium_driverless\types\target.py", line 26, in <module>
>     from selenium_driverless.utils.utils import safe_wrap_fut
>   File "C:\Users\....\....\.venv\Lib\site-packages\selenium_driverless\utils\utils.py", line 10, in <module>
>     import selenium
> ModuleNotFoundError: No module named 'selenium'

Would be nice to be able to get rid of Selenium :)

**Comment by ttlns** [comment]
Thanks!

To refactor:
https://github.com/kaliiiiiiiiii/Selenium-Driverless/blob/ca333fd88b0b7722ac128e08deccbb5ffbd66b39/src/selenium_driverless/utils/utils.py#L10
https://github.com/kaliiiiiiiiii/Selenium-Driverless/blob/ca333fd88b0b7722ac128e08deccbb5ffbd66b39/src/selenium_driverless/utils/utils.py#L74-L75

https://github.com/kaliiiiiiiiii/Selenium-Driverless/blob/ca333fd88b0b7722ac128e08deccbb5ffbd66b39/requirements.txt#L1
https://github.com/kaliiiiiiiiii/Selenium-Driverless/blob/ca333fd88b0b7722ac128e08deccbb5ffbd66b39/setup.py#L3
