### ISSUE TITLE
[feature request] implement `WebElement.screenshot`

### ISSUE THREAD

**Issue by fyxtc** [kaliiiiiiiiii/Selenium-Driverless#69]
Traceback (most recent call last):
  File "test.py", line 110, in main
    await btnEl.screenshot("slideImg.png")
  File "/Users/hikaru/.pyenv/versions/3.8.0/lib/python3.8/site-packages/selenium_driverless/types/webelement.py", line 584, in screenshot
    png = await self.screenshot_as_png
  File "/Users/hikaru/.pyenv/versions/3.8.0/lib/python3.8/site-packages/selenium_driverless/types/webelement.py", line 562, in screenshot_as_png
    res = await self.screenshot_as_base64
  File "/Users/hikaru/.pyenv/versions/3.8.0/lib/python3.8/site-packages/selenium_driverless/types/webelement.py", line 551, in screenshot_as_base64
    raise NotImplementedError()
NotImplementedError

**Comment by kaliiiiiiiiii** [comment]
@fyxtc so what? It tells you it's not implemented yet:)

**Comment by fyxtc** [comment]
@kaliiiiiiiiii Don't mind, I just for a request :)

**Comment by kaliiiiiiiiii** [comment]
@fyxtc surely:)
Let's merge this issue to https://github.com/kaliiiiiiiiii/Selenium-Driverless/issues/8

and I'll add it to the TODO's
