### ISSUE TITLE
Unable to close page after a TimeoutError

### ISSUE THREAD

**Issue by srichards2103** [kaliiiiiiiiii/Selenium-Driverless#83]
Hi, 

Not sure if this is an issue or a problem with my code. But my problem comes when I have tabs of a driver performing actions on different web pages in parallel. When one of the tabs hits a TimeoutError I am unable to close and reopen the page with the same url it was on. For example:

```
2023-10-04 21:36:51,539 ERROR page didn't load within timeout of 30
Traceback (most recent call last):
  File "/Users/srichards/.pyenv/versions/3.11.1/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/srichards/Documents/code/genv1/executor.py", line 697, in _get_odds_driverless
    market_data = await automation.update()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/srichards/Documents/code/genv1/bookies/ladbrokes.py", line 377, in update
    name = await row.find_element(By.CSS_SELECTOR, '[data-testid="runner-name"]')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/srichards/.pyenv/versions/3.11.1/lib/python3.11/site-packages/selenium_driverless/types/webelement.py", line 245, in find_element
    elems = await self.find_elements(by=by, value=value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/srichards/.pyenv/versions/3.11.1/lib/python3.11/site-packages/selenium_driverless/types/webelement.py", line 280, in find_elements
    res = await self.__target__.execute_cdp_cmd("DOM.querySelectorAll", {"nodeId": node_id,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/srichards/.pyenv/versions/3.11.1/lib/python3.11/site-packages/selenium_driverless/types/target.py", line 718, in execute_cdp_cmd
    result = await self.socket.exec(method=cmd, params=cmd_args, timeout=timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/srichards/.pyenv/versions/3.11.1/lib/python3.11/site-packages/cdp_socket/socket.py", line 73, in exec
    raise e
  File "/Users/srichards/.pyenv/versions/3.11.1/lib/python3.11/site-packages/cdp_socket/socket.py", line 69, in exec
    return await asyncio.wait_for(self._responses[_id], timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/srichards/.pyenv/versions/3.11.1/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/srichards/.pyenv/versions/3.11.1/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/srichards/Documents/code/genv1/executor.py", line 704, in _get_odds_driverless
    await automation.page.close(timeout=10)
  File "/Users/srichards/.pyenv/versions/3.11.1/lib/python3.11/site-packages/selenium_driverless/types/target.py", line 349, in close
    await self.execute_cdp_cmd("Page.close", timeout=timeout)
  File "/Users/srichards/.pyenv/versions/3.11.1/lib/python3.11/site-packages/selenium_driverless/types/target.py", line 718, in execute_cdp_cmd
    result = await self.socket.exec(method=cmd, params=cmd_args, timeout=timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/srichards/.pyenv/versions/3.11.1/lib/python3.11/site-packages/cdp_socket/socket.py", line 73, in exec
    raise e
  File "/Users/srichards/.pyenv/versions/3.11.1/lib/python3.11/site-packages/cdp_socket/socket.py", line 69, in exec
    return await asyncio.wait_for(self._responses[_id], timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/srichards/.pyenv/versions/3.11.1/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
```
Is there any other way to close the page without exiting the entire driver?

Thanks

**Comment by kaliiiiiiiiii** [comment]
please provide a minimum reproducible example script

**Comment by srichards2103** [comment]
```
async def _example(automation)
    try:
        elements = await automation.page.find_elements(By.CSS_SELECTOR, "[data-testid='example']")
        return elements
    except Exception as e:
        error_logger.error(e, exc_info=True)
        await automation.page.close(timeout=5)
        ## Re open page
        page = await self.driver.switch_to.new_window("tab", activate=False) 
        automation.page = page
        await page.get(automation.url)
        return None

futures = [ _example(automation) for automation in self.PAGES.values()]
examples = await asyncio.gather(*futures)
```
Each page of an automation is created by `page = await self.driver.switch_to.new_window("tab", activate=False)` before executing the code above. 

This is just an example block of code since I don't think you could reproduce it without access to the site I'm trying. Hope it still makes things clearer.

**Comment by kaliiiiiiiiii** [comment]
@srichards2103 
As I understand, the following code:
```python
from selenium_driverless.sync import webdriver
from selenium_driverless.utils.utils import read
from selenium_driverless import webdriver
import asyncio
global driver


async def target_1_handler(target):
    await target.get('https://abrahamjuliot.github.io/creepjs/')
    print(await target.title)


async def target_2_handler(target):
    await target.get("about:blank")
    await target.close()
    new_target = await driver.switch_to.new_window("tab", activate=False)
    await new_target.get("chrome://version")


async def main():
    global driver
    options = webdriver.ChromeOptions()
    async with webdriver.Chrome(options=options) as driver:
        target_1 = await driver.current_target
        target_2 = await driver.switch_to.new_window("tab", activate=False)
        await asyncio.gather(
            target_1_handler(target_1),
            target_2_handler(target_2)
        )
        await target_1.focus()
        input("press ENTER to exit")


asyncio.run(main())
```

would be a example code for what you trying to do. However, this runs just fine for me. 
1. Can you check if it runs as expected in your env as well?
3. if 1. is the case, then I won't be able to do resolve that issue & might close it **as not planned** after some time if I can't reproduce (or you find a fix) it.

**Comment by kaliiiiiiiiii** [comment]
@srichards2103
Pretty sure I found your issue. Considering the following script:
```python
from selenium_driverless import webdriver
from selenium_driverless.types.by import By
import traceback
import asyncio


async def main():
    options = webdriver.ChromeOptions()
    async with webdriver.Chrome(options=options) as driver:
        # some other target
        target_1 = driver.current_target

        target = await driver.switch_to.new_window("tab", activate=False)
        try:
            # always raises "NoSuchElementException"
            await target.find_element(By.CSS_SELECTOR, "[data-testid='example']")
        except Exception:
            traceback.print_exc()
            await target.close()
            new_target = await driver.switch_to.new_window("tab", activate=False)
            await new_target.get(target.url, timeout=5)
            input("press ENTEr to quit")


asyncio.run(main())
```
```
Traceback (most recent call last):
  File "C:\Users\aurin\AppData\Roaming\JetBrains\PyCharmCE2023.2\scratches\scratch_1.py", line 16, in main
    await target.find_element(By.CSS_SELECTOR, "[data-testid='example']")
  File "C:\Users\aurin\PycharmProjects\selenium_driverless\venv\lib\site-packages\selenium_driverless\types\target.py", line 547, in find_element
    return await parent.find_element(by=by, value=value, timeout=timeout)
  File "C:\Users\aurin\PycharmProjects\selenium_driverless\venv\lib\site-packages\selenium_driverless\types\webelement.py", line 249, in find_element
    raise NoSuchElementException()
selenium_driverless.types.webelement.NoSuchElementException
Traceback (most recent call last):
  File "C:\Users\aurin\PycharmProjects\selenium_driverless\venv\lib\site-packages\selenium_driverless\types\target.py", line 225, in get
    await wait
  File "C:\Users\aurin\PycharmProjects\selenium_driverless\venv\lib\site-packages\selenium_driverless\types\target.py", line 704, in wait_for_cdp
    return await self.socket.wait_for(event, timeout=timeout)
  File "C:\Users\aurin\PycharmProjects\selenium_driverless\venv\lib\site-packages\cdp_socket\socket.py", line 94, in wait_for
    raise e
  File "C:\Users\aurin\PycharmProjects\selenium_driverless\venv\lib\site-packages\cdp_socket\socket.py", line 89, in wait_for
    res = await asyncio.wait_for(_iter.__anext__(), timeout)
  File "C:\Users\aurin\AppData\Local\Programs\Python\Python37\lib\asyncio\tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\aurin\AppData\Local\Programs\Python\Python37\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\aurin\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\aurin\AppData\Roaming\JetBrains\PyCharmCE2023.2\scratches\scratch_1.py", line 21, in main
    await new_target.get(target.url, timeout=1)
  File "C:\Users\aurin\PycharmProjects\selenium_driverless\venv\lib\site-packages\selenium_driverless\types\target.py", line 227, in get
    raise TimeoutError(f"page didn't load within timeout of {timeout}")
TimeoutError: page didn't load within timeout of 1
python-BaseException
sys:1: RuntimeWarning: coroutine 'Target.url' was never awaited
Task exception was never retrieved
future: <Task finished coro=<Target.execute_cdp_cmd() done, defined at C:\Users\aurin\PycharmProjects\selenium_driverless\venv\lib\site-packages\selenium_driverless\types\target.py:721> exception=TypeError('Object of type coroutine is not JSON serializable')>
Traceback (most recent call last):
  File "C:\Users\aurin\PycharmProjects\selenium_driverless\venv\lib\site-packages\selenium_driverless\types\target.py", line 742, in execute_cdp_cmd
    result = await self.socket.exec(method=cmd, params=cmd_args, timeout=timeout)
  File "C:\Users\aurin\PycharmProjects\selenium_driverless\venv\lib\site-packages\cdp_socket\socket.py", line 66, in exec
    _id = await self.send(method=method, params=params)
  File "C:\Users\aurin\PycharmProjects\selenium_driverless\venv\lib\site-packages\cdp_socket\socket.py", line 60, in send
    await self._ws.send(json.dumps(_dict))
  File "C:\Users\aurin\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\aurin\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\aurin\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\aurin\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type coroutine is not JSON serializable
```
`target.url` won't return the url, because it hasn't been awaited.

Basically, you'll have to retrieve the url before the line which might throw an exception:
```python
from selenium_driverless import webdriver
from selenium_driverless.types.by import By
import traceback
import asyncio


async def main():
    options = webdriver.ChromeOptions()
    async with webdriver.Chrome(options=options) as driver:
        # some other target
        target_1 = driver.current_target

        target = await driver.switch_to.new_window("tab", activate=False)
        url = await target.url # get current url
        try:
            # always raises "NoSuchElementException"
            await target.find_element(By.CSS_SELECTOR, "[data-testid='example']")
        except Exception:
            traceback.print_exc()
            await target.close()
            new_target = await driver.switch_to.new_window("tab", activate=False)
            await new_target.get(url, timeout=1)
            input("press ENTEr to quit")

asyncio.run(main())
```
Please close this issue if it's resolved by that.

**Comment by srichards2103** [comment]
Hi @kaliiiiiiiiii ,

This isn't the issue since in my context the url is a property of an "automation" object. I also tested using google.com as the url to fetch but also did not work. It seems that once it times out from interacting with the webpage (such as finding elements), the timeout carries through to any other actions on the same page, rendering the page useless and with no way to close it. 

Any idea what this could be? Or do you have another way of closing the page which wouldn't timeout?

**Comment by kaliiiiiiiiii** [comment]
> Hi @kaliiiiiiiiii ,
> 
> This isn't the issue since in my context the url is a property of an "automation" object. I also tested using google.com as the url to fetch but also did not work. It seems that once it times out from interacting with the webpage (such as finding elements), the timeout carries through to any other actions on the same page, rendering the page useless and with no way to close it.
> 
> Any idea what this could be? Or do you have another way of closing the page which wouldn't timeout?

Wait a minute does the wollowing script work for you?
```python
from selenium_driverless import webdriver
from selenium_driverless.types.by import By
import traceback
import asyncio


async def main():
    options = webdriver.ChromeOptions()
    async with webdriver.Chrome(options=options) as driver:
        # some other target
        target_1 = driver.current_target

        target = await driver.switch_to.new_window("tab", activate=False)
        url = await target.url
        try:
            # always raises "NoSuchElementExecption"
            await target.get("https://nowsecure.nl/", wait_load=True, timeout=0.1)
        except Exception:
            traceback.print_exc()
            await target.close()
            new_target = await driver.switch_to.new_window("tab", activate=False)
            await new_target.get(url, timeout=1)
            input("press ENTEr to quit")

asyncio.run(main())
```

Tbh, I suspect a bug in Chrome.
What OS and Chrome version are you running on?

**Comment by srichards2103** [comment]
```
Traceback (most recent call last):
  File "/Users/srichards/.pyenv/versions/3.11.1/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/Users/srichards/.pyenv/versions/3.11.1/lib/python3.11/site-packages/cdp_socket/scripts/abstract.py", line 23, in __anext__
    return await self._fut
           ^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/srichards/.pyenv/versions/3.11.1/lib/python3.11/site-packages/selenium_driverless/types/target.py", line 222, in get
    await wait
  File "/Users/srichards/.pyenv/versions/3.11.1/lib/python3.11/site-packages/selenium_driverless/types/target.py", line 680, in wait_for_cdp
    return await self.socket.wait_for(event, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/srichards/.pyenv/versions/3.11.1/lib/python3.11/site-packages/cdp_socket/socket.py", line 93, in wait_for
    raise e
  File "/Users/srichards/.pyenv/versions/3.11.1/lib/python3.11/site-packages/cdp_socket/socket.py", line 88, in wait_for
    res = await asyncio.wait_for(_iter.__anext__(), timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/srichards/.pyenv/versions/3.11.1/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/srichards/Documents/code/genv1/tests/driver_timeout.py", line 17, in main
    await target.get("https://nowsecure.nl/", wait_load=True, timeout=0.1)
  File "/Users/srichards/.pyenv/versions/3.11.1/lib/python3.11/site-packages/selenium_driverless/types/target.py", line 224, in get
    raise TimeoutError(f"page didn't load within timeout of {timeout}")
TimeoutError: page didn't load within timeout of 0.1
```
This what you expect? Running MacOS with Chrome 117.

**Comment by kaliiiiiiiiii** [comment]
> ```
> Traceback (most recent call last):
>   File "/Users/srichards/.pyenv/versions/3.11.1/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
>     return fut.result()
>            ^^^^^^^^^^^^
>   File "/Users/srichards/.pyenv/versions/3.11.1/lib/python3.11/site-packages/cdp_socket/scripts/abstract.py", line 23, in __anext__
>     return await self._fut
>            ^^^^^^^^^^^^^^^
> asyncio.exceptions.CancelledError
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/Users/srichards/.pyenv/versions/3.11.1/lib/python3.11/site-packages/selenium_driverless/types/target.py", line 222, in get
>     await wait
>   File "/Users/srichards/.pyenv/versions/3.11.1/lib/python3.11/site-packages/selenium_driverless/types/target.py", line 680, in wait_for_cdp
>     return await self.socket.wait_for(event, timeout=timeout)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/srichards/.pyenv/versions/3.11.1/lib/python3.11/site-packages/cdp_socket/socket.py", line 93, in wait_for
>     raise e
>   File "/Users/srichards/.pyenv/versions/3.11.1/lib/python3.11/site-packages/cdp_socket/socket.py", line 88, in wait_for
>     res = await asyncio.wait_for(_iter.__anext__(), timeout)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/srichards/.pyenv/versions/3.11.1/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
>     raise exceptions.TimeoutError() from exc
> TimeoutError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/srichards/Documents/code/genv1/tests/driver_timeout.py", line 17, in main
>     await target.get("https://nowsecure.nl/", wait_load=True, timeout=0.1)
>   File "/Users/srichards/.pyenv/versions/3.11.1/lib/python3.11/site-packages/selenium_driverless/types/target.py", line 224, in get
>     raise TimeoutError(f"page didn't load within timeout of {timeout}")
> TimeoutError: page didn't load within timeout of 0.1
> ```
> 
> This what you expect? Running MacOS with Chrome 117.

assuming there's no exit after that (and `press ENTEr to quit` is shown in console), yes, that's expected.
Tbh at that point, I can't really do a lot on that issue. Seems to me like it depends on some other code you haven't shared.

**Comment by srichards2103** [comment]
Yeah no worries. I'll close this one since it must be an issue with my code. Thanks a lot for all your work!
